### ISSUE TITLE
Week 1 Day 4 - Computational Thinking Exercise

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#15]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/04-computational-thinking-exercise

Ready for review @amyealmeida @carmenejames 

No known issues :)

**Comment by amyealmeida** [comment]
@microsarah This is great! I just fixed some typos and formatting.

A couple questions:
1) Do you think that this will take the full hour?  Maybe we should add some language about there being 40 minutes for work on the problems and then 20 minutes to discuss as a class and talk through logic.
2) I think this needs to be organized differently so that the answers don't appear in the Exercise page along with the questions. If instructors share this page with students so that they see the questions, they will also see the answers!  Maybe we can put the answers in a folder?

**Comment by microsarah** [comment]
@amyealmeida this should be ready to close :)
